global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'streaming-stack'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # PostgreSQL Exporter (optional - add when you set up postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Kafka Exporter (optional - add when you set up kafka_exporter)
  # - job_name: 'kafka'
  #   static_configs:
  #     - targets: ['kafka-exporter:9308']

  # Add your custom application metrics here
  # - job_name: 'your-app'
  #   static_configs:
  #     - targets: ['your-app:port']

